<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="N-20HEPF10E801" failures="1" tests="1" name="com.selenium.practise.Dataprovider" time="0.008" errors="0" timestamp="9 Nov 2020 10:05:06 GMT">
  <testcase classname="com.selenium.practise.Dataprovider" name="data" time="0.008">
    <failure message="
The data provider is trying to pass 2 parameters but the method com.selenium.practise.Dataprovider#data takes 3 and TestNG is unable in inject a suitable object" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 2 parameters but the method com.selenium.practise.Dataprovider#data takes 3 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1367)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1365)
	... 17 more
]]>
    </failure>
  </testcase> <!-- data -->
</testsuite> <!-- com.selenium.practise.Dataprovider -->
